### ISSUE TITLE
Aan de linkerkant van "Conceptueel een baas" blijft heel weining over van het oranje streepje

### ISSUE THREAD

**Issue by alexhoogeboom** [newfishdev/indrukwekkend#66]

**Comment by odil-io** [comment]
Dat is iets waar we het met Indrukwekkend/Tarek over moeten hebben. Die zinnen krijgen progammatisch een `<br>` om de 3 woorden. Ik heb er over na gedacht dat ze dit zelf moeten invoegen. Maar dat gaf toen in de praktijk niet het gewenste resultaat.
