### ISSUE TITLE
Team en cases link

### ISSUE THREAD

**Issue by alexhoogeboom** [newfishdev/indrukwekkend#72]
Kan je zorgen dat deze na het klikken altijd bovenaan beginnen?
Wanneer ik op mijn mobiel de site bekijk, en een beetje naar beneden scroll, en vervolgens klik op "Bekijk ons werk", dan mis ik meteen al de eerste case, en moet ik omhoog scrollen om deze te bekijken.

**Comment by odil-io** [comment]
Zie #49
