### ISSUE TITLE
Oranje blok "overtuigen" social links te krap op elkaar op de tablet en mobiel

### ISSUE THREAD

**Issue by alexhoogeboom** [newfishdev/indrukwekkend#75]
Tablet:
![schermafbeelding 2017-09-08 om 16 29 48](https://user-images.githubusercontent.com/10241859/30216201-7f3a22ee-94b2-11e7-911e-25a3207a49e3.png)

Mobiel:
![schermafbeelding 2017-09-08 om 16 31 20](https://user-images.githubusercontent.com/10241859/30216239-a808e5ca-94b2-11e7-9f8b-3869eae1a770.png)

**Comment by odil-io** [comment]
Closed by `6fcdfb1`
