### ISSUE TITLE
Bug met Brands .slick() in front-page

### ISSUE THREAD

**Issue by odil-io** [newfishdev/indrukwekkend#92]
## Case:

Wanneer er minder dan 8 merken op de front-page staan, maakt .slick() er een slide van met 1 dot.
Dit probleem is niet aanwezig wanneer er meer dan 8 merken op de front-page worden gezet.

**Comment by hphioolen** [comment]
Vanwege het mobile verhaal waarbij er maar 3-op-een-rij kunnen, gaan we sowieso naar 6 ilv 8 logo's.
Ik denk dat dit probleem zich dan ook niet voor gaat doen

**Comment by odil-io** [comment]
Dan laat ik het zoals het nu is en zet ik het aantal logo's per slide op 6.

**Comment by odil-io** [comment]
Zie #93.
