### ISSUE TITLE
slider "merken" op de Homepage

### ISSUE THREAD

**Issue by hphioolen** [newfishdev/indrukwekkend#93]
## Case:

De merken staan in rijen van 4, maar alleen op XL, voorstel is nu om daar rijen van 3 van te maken. Dus in de slider komen er dan max 6 en niet 8.

**Comment by odil-io** [comment]
Opgelost door [`141f5f5`](https://github.com/newfishdev/indrukwekkend/commit/141f5f56911ae13bff7f46b38120be50b89c200d)
