### ISSUE TITLE
Handtekeningen variabel

### ISSUE THREAD

**Issue by odil-io** [newfishdev/indrukwekkend#97]
Het ACF veld 'autograph' word niet meer gebruikt.
Deze bevind zich nog in `quote-left.php` en `quote-right.php`.

** Suggestie **
Handtekening upload maken in post type 'teamleden' welke alleen .png accepteerd.
Formaat moet nog bepaald worden. Maar dit zal iets zijn van 250x100 zijn.

**Comment by hphioolen** [comment]
Ik heb de quotes nu samengevoegd op het bestand heading_right.php Quote left en right worden niet meer gebruikt.

Ik vind het ook niet erg als he met svg gaat en dan met een veld dat ingeladen wordt, dan zou je een pull down kunnen gebruiken, of hierin ook de titel van het teamlid.

**Comment by odil-io** [comment]
Is sinds [7818c54](https://github.com/newfishdev/indrukwekkend/commit/7818c54dc74dbbabb0dcb9a3abf5a47d385fb5ec) een invoer veld met de naam van het bestand in /images/autographs.
